# secrets management via .env (excluded via .gitignore)
dotenv: .env

networks:
    default: anvil
    development:
        host: http://127.0.0.1:8545  # Replace with your Anvil instance's URL and port
        gas_price: 1 # (1 wei)
        cmd_settings:
            # without this explicit setting chainid==1 is returend by block.chainid
            accounts: 20
            chain_id: 1337
    polygon:
        chainid: 137
        explorer: https://api.polygonscan.com/api
        host: https://polygon-mainnet.g.alchemy.com/v2/$WEB3_ALCHEMY_PROJECT_ID

# brownie default values made explicit
compiler:
    evm_version: null
    solc:
        version: 0.8.2
        executable: /home/vscode/.svm/0.8.2/solc-0.8.2
        optimizer:
            enabled: true
            runs: 200
        # https://eth-brownie.readthedocs.io/en/stable/compile.html#compiler-settings
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
            # audited versions below
            - "@etherisc/gif-interface=etherisc/gif-interface@2.0.0-rc.1"
            - "@etherisc/gif-contracts=etherisc/gif-contracts@2.0.0-rc.1-chainlink.1.3.13"

# packages below will be added to brownie
# you may use 'brownie pm list' after 'brownie compile' 
# to list the packages installed via the dependency list below
dependencies:
    # github dependency format: <owner>/<repository>@<release>
    - OpenZeppelin/openzeppelin-contracts@4.8.2
    # audited versions
    - etherisc/gif-interface@2.0.0-rc.1
    - etherisc/gif-contracts@2.0.0-rc.1-chainlink.1.3.13
