version: "3.8"

services:
  mongodb:
    image: mongo:7
    # ports:
    #   - "27017:27017"
    # volumes:
    # - mongodb_data:/data/db
  api:
    image: esusfarm-api
    ports:
      - "8002:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mongo

volumes:
  mongodb_data:
