version: "3.8"

services:
  # api:
  #   build: .
  #   container_name: api_esusfarm
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGO_USERNAME: root
  #     MONGO_PASSWORD: s3cret
  #     MONGO_HOSTNAME: mongodb
  #     MONGO_PORT: 27017
  #     # use a different db for production setups
  #     MONGO_DB: admin

  mongodb:
    image: mongo:latest
    container_name: mongodb_esusfarm
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: