version: '3'

services:
  mongo:
    image: mongo:6-jammy
  api:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: vscode
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9-bookworm
        PLATFORM: linux/amd64
    environment:
      - MONGO_URL=mongodb://mongo:27017/mongo
    volumes:
      - ..:/workspaces/esusfarm:cached
      #- $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

